version: '3.9'

services:
  apartments:
    build: ./apartments
    ports:
      - "3000:3000"
  bookings:
    build: ./bookings
    ports:
      - "3001:3000"
  postgres-apartment:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=MicroserviceApp
      - POSTGRES_USER=MicroserviceApp
      - POSTGRES_DB=ApartmentDB
  postgres-booking:
    image: postgres:14-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=MicroserviceApp
      - POSTGRES_USER=MicroserviceApp
      - POSTGRES_DB=BookingDB
