version: '3.9'

services:
  apartments:
    build: ./apartments
    ports:
      - "3000:3000"
    depends_on:
      - postgres-apartment
    environment:
      - PORT=3000
      - POSTGRES_HOST=postgres-apartment
      - POSTGRES_PORT=5432
      - MQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
  bookings:
    build: ./bookings
    ports:
      - "3001:3000"
    depends_on:
      - postgres-booking
    environment:
      - PORT=3000
      - POSTGRES_HOST=postgres-booking
      - POSTGRES_PORT=5432
      - MQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
      - APARTMENT_URL=http://apartments:3000
  # esbookings:
  #   build: ./esbookings
  #   ports:
  #     - "3001:3000"
  #   depends_on:
  #     - postgres-booking
  #   environment:
  #     - PORT=3000
  #     - POSTGRES_HOST=postgres-booking
  #     - POSTGRES_PORT=5432
  #     - MQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
  #     - APARTMENT_URL=http://apartments:3000  
  search:
    build: ./search
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - MQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
      - APARTMENT_URL=http://apartments:3000
      - BOOKING_URL=http://bookings:3000
  gateway:
    build: ./gateway
    ports:
      - "3333:3333"
    environment:
      - CONFIGURATION_FILE=configuration-deploy.yaml
  postgres-apartment:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=MicroserviceApp
      - POSTGRES_USER=MicroserviceApp
      - POSTGRES_DB=ApartmentDB
  postgres-booking:
    image: postgres:14-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=MicroserviceApp
      - POSTGRES_USER=MicroserviceApp
      - POSTGRES_DB=BookingDB
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672 # for the management console go to http://localhost:15672 the default user name is guest and password is also guest
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
