@apartment_service_url = localhost:3000
@booking_service_url = localhost:3001
@search_service_url = localhost:3002



### Create new aparment

POST http://{{apartment_service_url}}/api/apartments
Content-Type: application/json

{
    "name": "Hotel ABC", 
    "address": "Via Abc, 123"
}

### Search all apartments in apartments service

GET http://{{apartment_service_url}}/api/apartments


### Create a booking

POST http://{{booking_service_url}}/api/booking

{
    "appartmentID": 1,
    "startDate": "2023-12-01",
    "toDate": "2023-12-30"
}


### Search free apartments in search service

GET http://{{search_service_url}}/api/apartments/available?from=2023-01-02&to=2023-01-05
