@apartment_service_url = localhost:3000
@booking_service_url = localhost:3001
@search_service_url = localhost:3002



### Create new apartment

POST http://{{apartment_service_url}}/api/apartments
Content-Type: application/json

{
    "apartment_name": "Maybe White", 
    "address": "Trento",
    "noise_level": "5",
    "floor": "1"
}

### Delete apartment

DELETE http://{{apartment_service_url}}/api/apartments
Content-Type: application/json

{
    "id": "e7603c64-c3c8-40d9-a684-55a371f260df"
}

### Search all apartments in apartments service (debug endpoint)

GET http://{{apartment_service_url}}/api/apartments


### Get all bookings from booking service (debug endpoint)

GET http://{{booking_service_url}}/api/bookings


### Create a booking

POST http://{{booking_service_url}}/api/bookings

{
    "bookingID": "1e0cfb4e-0a11-48c8-a1f5-e82f5587818c",
    "apartmentID": "d7675c3b-b97e-45a3-87a8-80b46b4d1162",
    "userID": "M47730",
    "startDate": "2023-12-01",
    "endDate": "2023-12-31"
}


### Update Booking
PATCH http://{{booking_service_url}}/api/bookings
Content-Type: application/json

{
    "bookingID": "a4321c64-c3c8-40d9-a684-55a371f260df",
    "apartmentID": "d7675c3b-b97e-45a3-87a8-80b46b4d1162",
    "userID": "M47730",
    "startDate": "2023-11-01",
    "endDate": "2023-11-30"
}

### Delete Booking

DELETE http://{{booking_service_url}}/api/bookings
Content-Type: application/json

{
    "bookingID": "a9833c64-c3c8-40d9-a684-55a371f260df"
}

### Search free apartments in search service

GET http://{{search_service_url}}/api/apartments/available?from=2023-01-02&to=2023-01-05

