@apartment_service_url = localhost:3000
@booking_service_url = localhost:3001
@search_service_url = localhost:3002
@api_gatway_url = localhost:3333


######################### Apartment Service ###########################

### Get all apartments in apartments service

GET http://{{apartment_service_url}}/api/apartments


### Create new apartment in apartments service

POST http://{{apartment_service_url}}/api/apartments
Content-Type: application/json

{
    "apartment_name": "Always Green", 
    "address": "Bolzano",
    "noise_level": "5",
    "floor": "1"
}


### Delete apartment in apartments service

DELETE http://{{apartment_service_url}}/api/apartments
Content-Type: application/json

{
    "id": "2b56fca3-1502-40dc-bc60-9c74b8943169"
}


######################### Booking Service ###########################

### Get all bookings from bookings service

GET http://{{booking_service_url}}/api/bookings


### Create a booking in bookings service

POST http://{{booking_service_url}}/api/bookings

{
    "id": "{{$guid}}",
    "apartment_id": "7360c491-79e6-4c7e-9f51-df62d36e9da9",
    "user_id": "M47730",
    "start_date": "2025-03-01",
    "end_date": "2025-03-02"
}


### Update booking in bookings service
PATCH http://{{booking_service_url}}/api/bookings
Content-Type: application/json

{
    "id": "1e0cfb4e-0a11-48c8-a1f5-e82f5587818c",
    "apartment_id": "d7675c3b-b97e-45a3-87a8-80b46b4d1162",
    "user_id": "M47730",
    "start_date": "2023-11-01",
    "end_date": "2023-11-32"
}


### Delete booking in bookings service

DELETE http://{{booking_service_url}}/api/bookings
Content-Type: application/json

{
    "id": "58c0faed-ad6d-4660-91ec-52f3301e5a97"
}


######################### Search Service ###########################

### Search free apartments in search service

GET http://{{search_service_url}}/api/search/available?from=2023-02-02&to=2025-02-03


### Search all apartments in search service

GET http://{{search_service_url}}/api/search/apartments


### Search all bookings in search service

GET http://{{search_service_url}}/api/search/bookings
