# syntax=docker/dockerfile:1

FROM node:20.11.0 as base

WORKDIR /app

ENV NODE_ENV production

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

COPY . .

CMD node index.js
