# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build Apartments
      run: go build -v ./apartments

    - name: Test Appartments
      run: go test -v ./apartments
    
    - name: Build Bookings
      run: go build -v ./bookings

    - name: Test Bookings
      run: go test -v ./bookings
  
    - name: Build Gateway
      run: go build -v ./gateway

    - name: Test Bookings
      run: go test -v ./gateway
